services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=events_db
      - EVENTS_COLLECTION=events
      - LOG_LEVEL=info
    networks:
      - events-network
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27018:27017"
      # - "8080:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - events-network
    restart: unless-stopped

networks:
  events-network:
    driver: bridge

volumes:
  mongodb_data:

